### ISSUE TITLE
critical bug: library window cannot be reopened from reader windows (detach or back buttons) DB error, in DEV and PROD mode (`npm run start[:dev]`)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#532]
```
  readium-desktop:common:rectangle:window default window rectangle +1s
redux-saga error: uncaught at
at
 at
 at
 at bound x
 TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at GeneratorFunction.<anonymous> (/Volumes/500GB/Code/readium-desktop/dist/main.js:910:22469)
    at Generator.next (<anonymous>)
    at a (/Volumes/500GB/Code/readium-desktop/dist/main.js:16:1417)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by danielweck** [comment]
Related PR (merged): https://github.com/readium/readium-desktop/pull/524

**Comment by danielweck** [comment]
So, it looks like prod-mode LevelDB/Down introduces this bug (works fine with `npm run start:dev` with PouchDB JSON document backend)

**Comment by panaC** [comment]
Sorry, but I cannot reproduce this issue

**Comment by danielweck** [comment]
Have you tried *after* deleted the app's configuration folder (e.g. MacOS `Library/Application Support/EDRLab.Thorium`)?

**Comment by panaC** [comment]
Yes, it's works

**Comment by danielweck** [comment]
Did you reset your build?
From the tip of the `develop` branch:
* `rm -rf dist`
* `rm -rf node_modules`
* `npm install && npm __postinstall`
* `npm run start`

**Comment by danielweck** [comment]
I am now **unable* to reproduce the bug on MacOS (NPM `6.10.2`, NodeJS `10.16.0`):
1) branch `develop` https://github.com/readium/readium-desktop/commits/fd6e037d0da0a99e5bdd21f241beaf6cd63516162
2) `rm -rf node_modules`
3) `npm install`
4) `npm run __postinstall`
5) `rm -rf "~/Library/Application Support/EDRLab.ThoriumReader"`
6) `rm -rf dist`
7) `npm run start`
8) import EPUB
9) open EPUB (=> reader view replaces library/bookshelf view)
10) click "back" or "detach" button => was failing with error message (now works!)

**Comment by danielweck** [comment]
Re-opening, I can reproduce! (will post amended repro steps asap)
```
  readium-desktop:common:rectangle:window default window rectangle +1s
redux-saga error: uncaught at 
at  
 at  
 at  
 at bound x 
 TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at GeneratorFunction.<anonymous> (/Volumes/500GB/Code/readium-desktop/dist/main.js:910:22469)
    at Generator.next (<anonymous>)
    at a (/Volumes/500GB/Code/readium-desktop/dist/main.js:16:1417)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by danielweck** [comment]
Ok, I added step (8) in my revised step-by-step instructions:
https://github.com/readium/readium-desktop/issues/532#issuecomment-519080854

**Comment by danielweck** [comment]
Yep, step (8) is "DO NOT MOVE OR RESIZE ANY WINDOWS!".
If I move the library or the reader window at any point => error (can't get back to library view)

**Comment by danielweck** [comment]
Same error in dev mode! (`npm run start:dev`)

```
[2]   readium-desktop:common:rectangle:window default window rectangle +2s
[2] redux-saga error: uncaught at rootSaga
[2] at rootSaga 
[2]  at rootSaga 
[2]  at rootSaga 
[2]  at bound closeReader 
[2]  TypeError: Error processing argument at index 0, conversion failure from #<Object>
[2]     at GeneratorFunction.<anonymous> (/Volumes/500GB/Code/readium-desktop/dist/main.js:4158:28)
[2]     at Generator.next (<anonymous>)
[2]     at fulfilled (/Volumes/500GB/Code/readium-desktop/node_modules/tslib/tslib.js:107:62)
[2]     at process._tickCallback (internal/process/next_tick.js:68:7)
```
