### ISSUE TITLE
OPDS failure to resolve EPUB absolute URL

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#783]
http://opoto-ed.org/catalogue/opds
=>
http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fopoto-ed.org%2Fcatalogue%2Fopds
https://readium2.now.sh/opds-v1-v2-convert/http%3A%2F%2Fopoto-ed.org%2Fcatalogue%2Fopds

```
Error to fetch api
publication/importOpdsEntry
importOpdsPublication
TypeError
[ERR_INVALID_URL]: Invalid URL:
/catalogue/opds/titles/103/file/Cri+des+negres+suivi+de+textes+-+Anonymous.epub
```

The OPDS2 `link` is (note the relative URL):
```
               {
                    "href": "/catalogue/opds/titles/103/file/Cri+des+negres+suivi+de+textes+-+Anonymous.epub",
                    "type": "application/epub+zip",
                    "rel": "http://opds-spec.org/acquisition",
                }
```

(found in `By Newest` `The 30 most recent titles`)

**Comment by danielweck** [comment]
Culprit: `urlPathResolve` calls are missing in this code:

https://github.com/readium/readium-desktop/blob/80dbecabf4d8ea453c0917bb590020b32655744d/src/main/converter/opds.ts#L63-L160

**Comment by danielweck** [comment]
Also with this URL format:
`?lang=fr&format=mobi&page=Cahiers_de_la_quinzaine_-_XIII-6`

Test OPDS:
https://tools.wmflabs.org/wsexport/wikisource-fr-good.atom

**Comment by danielweck** [comment]
```
[2]   readium-desktop:main#redux/sagas/api publication importOpdsEntry [ 'https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=atom&page=Cahiers_de_la_quinzaine_-_XIII-6',
[2]   null,
[2]   'Cahiers de la quinzaine - XIII-6 Les événements actuels en Russie',
[2]   [],
[2]   null ] +99ms
[2]   readium-desktop:sync ### action type DOWNLOAD_REQUEST +1ms
[2]   readium-desktop:sync ### action type TOAST_OPEN_REQUEST +0ms
[2]   readium-desktop:main#services/catalog Import OPDS publication https://tools.wmflabs.org/wsexport/tool/book.php?lang=fr&format=atom&page=Cahiers_de_la_quinzaine_-_XIII-6 +0ms
[2]   readium-desktop:main#services/catalog Unable to retrieve opds publication OPDSPublication {
[2]   Metadata:
[2]    Metadata {
[2]      Title: 'Cahiers de la quinzaine - XIII-6',
[2]      Identifier:
[2]       'https://fr.wikisource.org/wiki/Cahiers_de_la_quinzaine_-_XIII-6',
[2]      Modified: 2019-10-11T08:33:16.000Z,
[2]      PublicationDate: undefined,
[2]      Rights: undefined },
[2]   Links:
[2]    [ OPDSLink {
[2]        Href: '?lang=fr&format=atom&page=Cahiers_de_la_quinzaine_-_XIII-6',
[2]        TypeLink: 'application/atom+xml;type=entry;profile=opds-catalog',
[2]        Rel: [Array],
[2]        Title: undefined },
[2]      OPDSLink {
[2]        Href:
[2]         'https://fr.wikisource.org/wiki/Cahiers_de_la_quinzaine_-_XIII-6',
[2]        TypeLink: 'text/html',
[2]        Rel: [Array],
[2]        Title: undefined },
[2]      OPDSLink {
[2]        Href: '?lang=fr&format=epub&page=Cahiers_de_la_quinzaine_-_XIII-6',
[2]        TypeLink: 'application/epub+zip',
[2]        Rel: [Array],
[2]        Title: undefined },
[2]      OPDSLink {
[2]        Href: '?lang=fr&format=mobi&page=Cahiers_de_la_quinzaine_-_XIII-6',
[2]        TypeLink: 'application/x-mobipocket-ebook',
[2]        Rel: [Array],
[2]        Title: undefined },
[2]      OPDSLink {
[2]        Href:
[2]         '?lang=fr&format=xhtml&page=Cahiers_de_la_quinzaine_-_XIII-6',
[2]        TypeLink: 'application/xhtml+xml',
[2]        Rel: [Array],
[2]        Title: undefined } ] } { TypeError [ERR_INVALID_URL]: Invalid URL: ?lang=fr&format=epub&page=Cahiers_de_la_quinzaine_-_XIII-6
[2]     at onParseError (internal/url.js:237:17)
[2]     at parse (internal/url.js:246:3)
[2]     at new URL (internal/url.js:321:5)
[2]     at Downloader.addDownload (/x/readium-desktop/dist/main.js:5494:24)
[2]     at CatalogService.<anonymous> (/x/readium-desktop/dist/main.js:5212:46)
[2]     at Generator.next (<anonymous>)
[2]     at /x/readium-desktop/node_modules/tslib/tslib.js:110:75
[2]     at new Promise (<anonymous>)
[2]     at Object.__awaiter (/x/readium-desktop/node_modules/tslib/tslib.js:106:16)
[2]     at CatalogService.importOpdsPublication (/x/readium-desktop/dist/main.js:5188:24)
[2]     at CatalogService.<anonymous> (/x/readium-desktop/dist/main.js:5177:52)
[2]     at Generator.next (<anonymous>)
[2]     at /x/readium-desktop/node_modules/tslib/tslib.js:110:75
[2]     at new Promise (<anonymous>)
[2]     at Object.__awaiter (/x/readium-desktop/node_modules/tslib/tslib.js:106:16)
[2]     at http_1.httpGet (/x/readium-desktop/dist/main.js:5152:76)
[2]   input: '?lang=fr&format=epub&page=Cahiers_de_la_quinzaine_-_XIII-6' } +863ms
[2]   readium-desktop:main#redux/sagas/api Error: Unable to retrieve opds publication: TypeError [ERR_INVALID_URL]: Invalid URL: ?lang=fr&format=epub&page=Cahiers_de_la_quinzaine_-_XIII-6
[2]   readium-desktop:main#redux/sagas/api     at CatalogService.<anonymous> (/x/readium-desktop/dist/main.js:5181:27)
[2]   readium-desktop:main#redux/sagas/api     at Generator.throw (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at rejected (/x/readium-desktop/node_modules/tslib/tslib.js:108:69)
[2]   readium-desktop:main#redux/sagas/api     at process._tickCallback (internal/process/next_tick.js:68:7) +864ms
[2]   readium-desktop:sync ### action type API_ERROR +863ms
[2]   readium-desktop:renderer:bookshelf_ Error to fetch api publication/importOpdsEntry Unable to retrieve opds publication: TypeError [ERR_INVALID_URL]: Invalid URL: ?lang=fr&format=epub&page=Cahiers_de_la_quinzaine_-_XIII-6 +2m
```
