### ISSUE TITLE
When OPDS feed does not have search link, exception in console (but app does not crash)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#784]
http://opoto-ed.org/catalogue/opds
=>
http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fopoto-ed.org%2Fcatalogue%2Fopds
https://readium2.now.sh/opds-v1-v2-convert/http%3A%2F%2Fopoto-ed.org%2Fcatalogue%2Fopds

`getSearchUrlFromOpds1Feed TypeError: Cannot read property 'TypeLink' of undefined`

```
[2]   readium-desktop:main#redux/sagas/api opds browse [ 'http://opoto-ed.org/catalogue/opds' ] +2s
[2]   readium-desktop:src/main/api/opds opdsFeed content-type application/atom+xml;profile=opds-catalog;kind=navigation +4s
[2]   readium-desktop:main/converter/opds getSearchUrlFromOpds1Feed TypeError: Cannot read property 'TypeLink' of undefined
[2]     at OpdsFeedViewConverter.<anonymous> (/x/readium-desktop/dist/main.js:2638:36)
[2]     at Generator.next (<anonymous>)
[2]     at /x/readium-desktop/node_modules/tslib/tslib.js:110:75
[2]     at new Promise (<anonymous>)
[2]     at Object.__awaiter (/x/readium-desktop/node_modules/tslib/tslib.js:106:16)
[2]     at OpdsFeedViewConverter.getSearchUrlFromOpds1Feed (/x/readium-desktop/dist/main.js:2633:24)
[2]     at OpdsFeedViewConverter.<anonymous> (/x/readium-desktop/dist/main.js:2605:40)
[2]     at Generator.next (<anonymous>)
[2]     at /x/readium-desktop/node_modules/tslib/tslib.js:110:75
[2]     at new Promise (<anonymous>)
[2]     at Object.__awaiter (/x/readium-desktop/node_modules/tslib/tslib.js:106:16)
[2]     at OpdsFeedViewConverter.convertOpdsFeedToView (/x/readium-desktop/dist/main.js:2580:24)
[2]     at OpdsApi.<anonymous> (/x/readium-desktop/dist/main.js:1887:70)
[2]     at Generator.next (<anonymous>)
[2]     at /x/readium-desktop/node_modules/tslib/tslib.js:110:75
[2]     at new Promise (<anonymous>) +3m
```

**Comment by danielweck** [comment]
Culprit: no sanity check on undefined `searchLink` in this code:
https://github.com/readium/readium-desktop/blob/80dbecabf4d8ea453c0917bb590020b32655744d/src/main/converter/opds.ts#L228-L229
