### ISSUE TITLE
bug on getSearchUrlFromOpds1Feed

### ISSUE THREAD

**Issue by panaC** [readium/readium-desktop#823]
http://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Finstantclassics.librarysimplified.org%2Fchildrens-books.xml

debug:
```
readium-desktop:main/converter/opds getSearchUrlFromOpds1Feed TypeError: doc.Url.find is not a function
[2]     at OpdsFeedViewConverter.<anonymous> (/goinfre/thorium/dist/main.js:2658:53)
[2]     at Generator.next (<anonymous>)
[2]     at fulfilled (/goinfre/thorium/node_modules/tslib/tslib.js:107:62)
[2]     at processTicksAndRejections (internal/process/task_queues.js:89:5) +2s
```

Link:
```
{
            "href": "https://instantclassics.librarysimplified.org/search",
            "type": "application/opensearchdescription+xml",
            "rel": "search"
        },
```

search:
```
<?xml version="1.0" encoding="UTF-8"?>
 <OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <ShortName>Search</ShortName>
   <Description>Search</Description>
   <Tags></Tags>
   <Url type="application/atom+xml;profile=opds-catalog" template="https://instantclassics.librarysimplified.org/search?q={searchTerms}"/>
 </OpenSearchDescription>
```

discovered on #786 , with the fix of convertMultiLangStringToString

**Comment by panaC** [comment]
```
'https://circulation.librarysimplified.org/NYNYPL/search/?entrypoint=All'                                                                                                                

<?xml version="1.0" encoding="UTF-8"?>
 <OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
   <ShortName>Search</ShortName>
   <Description>Search The New York Public Library</Description>
   <Tags>the-new-york-public-library</Tags>
   <Url type="application/atom+xml;profile=opds-catalog" template="https://circulation.librarysimplified.org/NYNYPL/search/?entrypoint=All&amp;q={searchTerms}"/>
 </OpenSearchDescription>%                                                                                                                                                                                                               

'http://static.wolnelektury.pl/opensearch.xml'                                                                                                                                        \
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/"
                       xmlns:atom="http://www.w3.org/2005/Atom"
                       xmlns:moz="http://www.mozilla.org/2006/browser/search/">
    <ShortName>Wolne Lektury</ShortName>
    <Description>Biblioteka internetowa WolneLektury.pl</Description>
    <InputEncoding>UTF-8</InputEncoding>
    <Tags>lektury</Tags>
    <Developer>Fundacja Nowoczesna Polska</Developer>
    <Language>pl</Language>
    <Contact>fundacja@nowoczesnapolska.org.pl</Contact>
    <Image height="16" width="16" type="image/x-icon">https://static.wolnelektury.pl/static/img/favicon.ico</Image>
    <Image height="64" width="64" type="image/png">https://static.wolnelektury.pl/static/img/wl_icon_64.png</Image>
    <Url type="application/atom+xml;profile=opds-catalog"
        template="https://wolnelektury.pl/opds/search/?q={searchTerms}&amp;author={atom:author}&amp;translator={atom:contributor}&amp;title={atom:title}" />
    <Url type="text/html" method="GET" template="https://wolnelektury.pl/szukaj/?q={searchTerms}" />
    <Url type="application/x-suggestions+json" method="GET" template="https://www.wolnelektury.pl/katalog/jtags/?mozhint=1&amp;q={searchTerms}" />
    <moz:SearchForm>https://wolnelektury.pl/</moz:SearchForm>
    <Query role="example" searchTerms="słowa" />
</OpenSearchDescription>
```

**Comment by panaC** [comment]
query param : http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fmanybooks.net%2Fopds%2F

opensearch : http://readium2.herokuapp.com/opds-v1-v2-convert/http%3A%2F%2Fwww.wolnelektury.pl%2Fopds
http://readium2.herokuapp.com/opds-v1-v2-convert/https%3A%2F%2Fframabookin.org%2Fb%2Fopds%2Ftitleslist%2F0%2F
...

**Comment by panaC** [comment]
opds2: https://catalog.feedbooks.com/catalog/index.json

**Comment by panaC** [comment]
handle opds2 search : https://drafts.opds.io/opds-2.0#2-search

```
{
type: "application/opds+json",
rel: "search",
href: "https://catalog.feedbooks.com/search.json{?query}",
templated: true
},
```
