### ISSUE TITLE
OPDS2 feeds => crash

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#851]
https://test.opds.io/2.0/home.json
or
https://catalog.feedbooks.com/catalog/index.json

```
[2]   readium-desktop:main#redux/sagas/api opds browse [
[2]   'https://catalog.feedbooks.com/publicdomain/browse/en/top.json?cat=FBBIO000000'
[2] ] +993ms
[2]   readium-desktop:src/main/api/opds opdsFeed content-type application/opds+json; charset=utf-8 +1s
[2]   readium-desktop:main#redux/sagas/api TypeError: Cannot read property 'filter' of undefined
[2]   readium-desktop:main#redux/sagas/api     at /readium-desktop/dist/main.js:3210:76
[2]   readium-desktop:main#redux/sagas/api     at Array.filter (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at OpdsFeedViewConverter.convertOpdsPublicationToView (/readium-desktop/dist/main.js:3210:52)
[2]   readium-desktop:main#redux/sagas/api     at /readium-desktop/dist/main.js:3264:33
[2]   readium-desktop:main#redux/sagas/api     at Array.map (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at OpdsFeedViewConverter.<anonymous> (/readium-desktop/dist/main.js:3263:64)
[2]   readium-desktop:main#redux/sagas/api     at Generator.next (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at /readium-desktop/node_modules/tslib/tslib.js:110:75
[2]   readium-desktop:main#redux/sagas/api     at new Promise (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at Object.__awaiter (/readium-desktop/node_modules/tslib/tslib.js:106:16)
[2]   readium-desktop:main#redux/sagas/api     at OpdsFeedViewConverter.convertOpdsFeedToView (/readium-desktop/dist/main.js:3254:24)
[2]   readium-desktop:main#redux/sagas/api     at OpdsApi.<anonymous> (/readium-desktop/dist/main.js:2620:70)
[2]   readium-desktop:main#redux/sagas/api     at Generator.next (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at /readium-desktop/node_modules/tslib/tslib.js:110:75
[2]   readium-desktop:main#redux/sagas/api     at new Promise (<anonymous>)
[2]   readium-desktop:main#redux/sagas/api     at Object.__awaiter (/readium-desktop/node_modules/tslib/tslib.js:106:16) +599ms
```

**Comment by danielweck** [comment]
TODO: test again with the code in the current `develop` branch (I believe this was fixed).
