### ISSUE TITLE
LCP LSD license update on Windows => book.epub disappear on app exit (instead of deleting immediately), and book.tmplcpl file remains

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#884]
Seems like the bug persists: https://github.com/readium/readium-desktop/issues/787

**Comment by danielweck** [comment]
Code culprit (no idea how to make the Windows filesystem happy ... our code releases file handles correctly as far as I can tell, it looks like there are stale file pointers hanging around because of how NodeJS implement filesystem access on Windows?):
https://github.com/readium/readium-desktop/blob/e9e2f52e35ef02c96f080d45760047d63bac2f0d/src/main/services/lcp.ts#L70-L102

**Comment by danielweck** [comment]
One drastic solution would be to exit the app and restart it ... not the ideal UX though !

**Comment by danielweck** [comment]
The problem only occurs when the book has been read at least once (i.e. streamer component accesses the ZIP resources). So it looks like the destroy/free function of streamer does not work because of a bug in the NodeJS stream/filesystem implementation on Windows (or maybe a bug in `Yauzl`, the ZIP library which is used to stream data out of the EPUB).
Regardless, there is a delayed file deletion on Windows, `book.epub` only disappears when the app exits. The good news is that the `book.tmplcpl` remains in the folder, so we could just rename it at a convenient time in order to work around the problem.

**Comment by danielweck** [comment]
Streamer release:
https://github.com/readium/r2-streamer-js/blob/babf82a69af82c50ed8421cea3fd7fda115ce0b4/src/http/server.ts#L360-L369

Publication release:
https://github.com/readium/r2-shared-js/blob/b0cc3a2b36cc2209508e5a9bb0ec8dfe5a353a22/src/models/publication.ts#L133-L142

**Comment by danielweck** [comment]
```
[2]   readium-desktop:main#services/lcp Error: EPERM: operation not permitted, rename 'C:\Users\danie\AppData\Roaming\EDRLab.ThoriumReader\publications\35085bad-e0b8-4dc7-a9a9-93d01a2ceb62\book.epub.tmplcpl' -> 'C:\Users\danie\AppData\Roaming\EDRLab.ThoriumReader\publications\35085bad-e0b8-4dc7-a9a9-93d01a2ceb62\book.epub'
[2]   readium-desktop:main#services/lcp     at Object.renameSync (fs.js:609:3)
[2]   readium-desktop:main#services/lcp     at LcpManager.<anonymous> (C:\Users\danie\Desktop\readium-desktop\dist\main.js:7172:16)
[2]   readium-desktop:main#services/lcp     at Generator.next (<anonymous>)
[2]   readium-desktop:main#services/lcp     at fulfilled (C:\Users\danie\Desktop\readium-desktop\node_modules\tslib\tslib.js:107:62) +381ms
[2]   readium-desktop:main#services/lcp Error: EPERM: operation not permitted, rename 'C:\Users\danie\AppData\Roaming\EDRLab.ThoriumReader\publications\35085bad-e0b8-4dc7-a9a9-93d01a2ceb62\book.epub.tmplcpl' -> 'C:\Users\danie\AppData\Roaming\EDRLab.ThoriumReader\publications\35085bad-e0b8-4dc7-a9a9-93d01a2ceb62\book.epub'
[2]   readium-desktop:main#services/lcp     at Object.renameSync (fs.js:609:3)
[2]   readium-desktop:main#services/lcp     at LcpManager.<anonymous> (C:\Users\danie\Desktop\readium-desktop\dist\main.js:7172:16)
[2]   readium-desktop:main#services/lcp     at Generator.next (<anonymous>)
[2]   readium-desktop:main#services/lcp     at fulfilled (C:\Users\danie\Desktop\readium-desktop\node_modules\tslib\tslib.js:107:62) +1ms
```
